-- Expand cities table to cover 50-mile radius from Dallas and Fort Worth

-- Add unique constraint if not exists (safe to run multiple times)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cities_name_unique') THEN
    ALTER TABLE cities ADD CONSTRAINT cities_name_unique UNIQUE (name);
  END IF;
END $$;

INSERT INTO cities (name) VALUES
  -- Already in CITY_COORDS but missing from cities table
  ('Frisco'),
  ('Burleson'),
  ('Weatherford'),
  ('Waxahachie'),
  ('Southlake'),
  ('Keller'),
  ('Grapevine'),
  ('Lewisville'),
  ('Flower Mound'),
  ('Crowley'),
  ('Granbury'),
  ('Mineral Wells'),
  ('Ennis'),
  ('Wylie'),
  ('Allen'),
  ('Prosper'),
  ('Celina'),
  ('Forney'),
  ('Saginaw'),
  ('Benbrook'),
  ('White Settlement'),
  ('Haltom City'),
  ('North Richland Hills'),
  ('Bedford'),
  ('Euless'),
  ('Hurst'),
  ('Coppell'),
  ('Lancaster'),
  ('Duncanville'),
  ('Kennedale'),
  ('Red Oak'),
  ('Glenn Heights'),
  ('Wilmer'),
  ('Sachse'),
  -- North
  ('Sherman'),
  ('Gainesville'),
  ('Pilot Point'),
  ('Sanger'),
  ('Aubrey'),
  ('Melissa'),
  ('Anna'),
  ('Van Alstyne'),
  ('Argyle'),
  ('Corinth'),
  ('Highland Village'),
  ('The Colony'),
  ('Roanoke'),
  ('Trophy Club'),
  ('Lake Dallas'),
  ('Cross Roads'),
  ('Krum'),
  -- Northeast
  ('Greenville'),
  ('Royse City'),
  ('Fate'),
  ('Heath'),
  ('Lavon'),
  ('Nevada'),
  ('Caddo Mills'),
  ('Quinlan'),
  ('Farmersville'),
  -- East
  ('Crandall'),
  ('Wills Point'),
  ('Canton'),
  -- Southeast
  ('Corsicana'),
  ('Palmer'),
  ('Garrett'),
  ('Bardwell'),
  ('Kemp'),
  -- South
  ('Itasca'),
  ('Rio Vista'),
  ('Grandview'),
  ('Keene'),
  ('Glen Rose'),
  -- Southwest
  ('Cresson'),
  ('Aledo'),
  ('Willow Park'),
  ('Hudson Oaks'),
  -- West
  ('Springtown'),
  ('Millsap'),
  -- Northwest
  ('Decatur'),
  ('Bridgeport'),
  ('Rhome'),
  ('Newark'),
  ('Boyd'),
  ('Paradise'),
  -- Central/Metro
  ('Richardson'),
  ('Addison'),
  ('Farmers Branch'),
  ('Murphy'),
  ('Rowlett'),
  ('Balch Springs'),
  ('Seagoville'),
  ('Sunnyvale'),
  ('Forest Hill'),
  ('River Oaks'),
  ('Watauga'),
  ('Richland Hills'),
  ('Pantego'),
  ('Ovilla'),
  ('Combine')
ON CONFLICT (name) DO NOTHING;
