-- 026_seed_cities_within_150mi.sql
-- Seed every city within ~150 miles of Denver and Dallas/Fort Worth so the
-- customer brain never fires "Customer order needs manual city assignment"
-- for a real geocoded address inside our service area.
--
-- Safe to re-run: ON CONFLICT updates is_active and avoids duplicates.

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cities_name_unique') THEN
    ALTER TABLE cities ADD CONSTRAINT cities_name_unique UNIQUE (name);
  END IF;
END $$;

DO $$ BEGIN
  ALTER TABLE cities ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
END $$;

INSERT INTO cities (name, state, is_active) VALUES
  -- ── COLORADO: Denver metro core ──
  ('Denver','CO',true),
  ('Aurora','CO',true),
  ('Lakewood','CO',true),
  ('Thornton','CO',true),
  ('Arvada','CO',true),
  ('Westminster','CO',true),
  ('Centennial','CO',true),
  ('Englewood','CO',true),
  ('Wheat Ridge','CO',true),
  ('Littleton','CO',true),
  ('Northglenn','CO',true),
  ('Commerce City','CO',true),
  ('Parker','CO',true),
  ('Brighton','CO',true),
  ('Greenwood Village','CO',true),
  ('Edgewater','CO',true),
  ('Sheridan','CO',true),
  ('Federal Heights','CO',true),
  ('Lone Tree','CO',true),
  ('Golden','CO',true),
  ('Highlands Ranch','CO',true),
  ('Cherry Hills Village','CO',true),
  ('Castle Rock','CO',true),
  ('Castle Pines','CO',true),
  ('Glendale','CO',true),
  ('Mountain View','CO',true),
  ('Lakeside','CO',true),
  ('Bow Mar','CO',true),
  ('Columbine Valley','CO',true),
  ('Foxfield','CO',true),
  ('Morrison','CO',true),
  -- ── COLORADO: Boulder county ──
  ('Boulder','CO',true),
  ('Longmont','CO',true),
  ('Broomfield','CO',true),
  ('Erie','CO',true),
  ('Lafayette','CO',true),
  ('Louisville','CO',true),
  ('Superior','CO',true),
  ('Niwot','CO',true),
  ('Gunbarrel','CO',true),
  ('Nederland','CO',true),
  ('Jamestown','CO',true),
  ('Ward','CO',true),
  ('Allenspark','CO',true),
  ('Lyons','CO',true),
  -- ── COLORADO: Adams / Weld county north ──
  ('Dacono','CO',true),
  ('Frederick','CO',true),
  ('Firestone','CO',true),
  ('Mead','CO',true),
  ('Johnstown','CO',true),
  ('Berthoud','CO',true),
  ('Severance','CO',true),
  ('Eaton','CO',true),
  ('Ault','CO',true),
  ('Pierce','CO',true),
  ('Nunn','CO',true),
  ('Carr','CO',true),
  ('Wellington','CO',true),
  ('Timnath','CO',true),
  ('Windsor','CO',true),
  ('Milliken','CO',true),
  ('Platteville','CO',true),
  ('Gilcrest','CO',true),
  ('La Salle','CO',true),
  ('Evans','CO',true),
  ('Greeley','CO',true),
  ('Kersey','CO',true),
  ('Hudson','CO',true),
  ('Keenesburg','CO',true),
  ('Fort Lupton','CO',true),
  ('Lochbuie','CO',true),
  -- ── COLORADO: Larimer / Fort Collins area ──
  ('Fort Collins','CO',true),
  ('Loveland','CO',true),
  ('Estes Park','CO',true),
  ('Drake','CO',true),
  ('Glen Haven','CO',true),
  ('Red Feather Lakes','CO',true),
  ('Livermore','CO',true),
  ('Bellvue','CO',true),
  ('Laporte','CO',true),
  -- ── COLORADO: Colorado Springs corridor ──
  ('Colorado Springs','CO',true),
  ('Monument','CO',true),
  ('Palmer Lake','CO',true),
  ('Larkspur','CO',true),
  ('Sedalia','CO',true),
  ('Franktown','CO',true),
  ('Elizabeth','CO',true),
  ('Kiowa','CO',true),
  ('Elbert','CO',true),
  ('Black Forest','CO',true),
  ('Falcon','CO',true),
  ('Peyton','CO',true),
  ('Calhan','CO',true),
  ('Ramah','CO',true),
  ('Manitou Springs','CO',true),
  ('Cascade','CO',true),
  ('Green Mountain Falls','CO',true),
  ('Woodland Park','CO',true),
  ('Divide','CO',true),
  ('Florissant','CO',true),
  ('Cripple Creek','CO',true),
  ('Victor','CO',true),
  ('Fountain','CO',true),
  ('Security-Widefield','CO',true),
  ('Stratmoor','CO',true),
  ('Cimarron Hills','CO',true),
  ('Gleneagle','CO',true),
  -- ── COLORADO: Mountain communities west of Denver ──
  ('Idaho Springs','CO',true),
  ('Georgetown','CO',true),
  ('Silver Plume','CO',true),
  ('Empire','CO',true),
  ('Black Hawk','CO',true),
  ('Central City','CO',true),
  ('Evergreen','CO',true),
  ('Conifer','CO',true),
  ('Bailey','CO',true),
  ('Pine','CO',true),
  ('Pine Junction','CO',true),
  ('Indian Hills','CO',true),
  ('Kittredge','CO',true),
  ('Genesee','CO',true),
  ('Aspen Park','CO',true),
  ('Tiny Town','CO',true),
  ('Buffalo Creek','CO',true),
  -- ── COLORADO: Eastern plains ──
  ('Bennett','CO',true),
  ('Strasburg','CO',true),
  ('Byers','CO',true),
  ('Watkins','CO',true),
  ('Deer Trail','CO',true),
  ('Agate','CO',true),
  ('Limon','CO',true),
  ('Hugo','CO',true),
  ('Genoa','CO',true),
  ('Arriba','CO',true),
  ('Flagler','CO',true),
  ('Last Chance','CO',true),
  ('Akron','CO',true),
  ('Otis','CO',true),
  ('Yuma','CO',true),
  ('Wray','CO',true),
  ('Burlington','CO',true),
  -- ── COLORADO: Pueblo direction (south-southeast) ──
  ('Pueblo','CO',true),
  ('Pueblo West','CO',true),
  ('Penrose','CO',true),
  ('Florence','CO',true),
  ('Canon City','CO',true),
  ('Lincoln Park','CO',true),
  ('Salida','CO',true),
  ('Buena Vista','CO',true),
  ('Westcliffe','CO',true),
  ('Walsenburg','CO',true),
  -- ── COLORADO: North/northeast plains toward Sterling ──
  ('Roggen','CO',true),
  ('Wiggins','CO',true),
  ('Fort Morgan','CO',true),
  ('Brush','CO',true),
  ('Snyder','CO',true),
  ('Sterling','CO',true),
  ('Crook','CO',true),
  -- ── TEXAS: DFW core (must-haves — likely already in table but make sure) ──
  ('Dallas','TX',true),
  ('Fort Worth','TX',true),
  ('Arlington','TX',true),
  ('Plano','TX',true),
  ('Garland','TX',true),
  ('Irving','TX',true),
  ('Mesquite','TX',true),
  ('McKinney','TX',true),
  ('Carrollton','TX',true),
  ('Denton','TX',true),
  ('Mansfield','TX',true),
  ('Grand Prairie','TX',true),
  ('DeSoto','TX',true),
  ('Cedar Hill','TX',true),
  ('Rockwall','TX',true),
  ('Rowlett','TX',true),
  ('Mckinney','TX',true),
  -- ── TEXAS: East Texas (Tyler / Longview corridor) ──
  ('Tyler','TX',true),
  ('Whitehouse','TX',true),
  ('Lindale','TX',true),
  ('Bullard','TX',true),
  ('Flint','TX',true),
  ('Chandler','TX',true),
  ('Mineola','TX',true),
  ('Quitman','TX',true),
  ('Athens','TX',true),
  ('Mabank','TX',true),
  ('Gun Barrel City','TX',true),
  ('Eustace','TX',true),
  ('Trinidad','TX',true),
  ('Malakoff','TX',true),
  -- ── TEXAS: Waco corridor ──
  ('Waco','TX',true),
  ('Hewitt','TX',true),
  ('Robinson','TX',true),
  ('Bellmead','TX',true),
  ('Lacy Lakeview','TX',true),
  ('Woodway','TX',true),
  ('Lorena','TX',true),
  ('McGregor','TX',true),
  ('Hillsboro','TX',true),
  ('West','TX',true),
  ('Mart','TX',true),
  ('Marlin','TX',true),
  ('Crawford','TX',true),
  ('Whitney','TX',true),
  ('Aquilla','TX',true),
  ('Penelope','TX',true),
  ('Mexia','TX',true),
  ('Fairfield','TX',true),
  ('Teague','TX',true),
  ('Wortham','TX',true),
  ('Groesbeck','TX',true),
  -- ── TEXAS: Northeast Texas ──
  ('Sulphur Springs','TX',true),
  ('Mount Pleasant','TX',true),
  ('Mount Vernon','TX',true),
  ('Winnsboro','TX',true),
  ('Pittsburg','TX',true),
  ('Daingerfield','TX',true),
  ('Paris','TX',true),
  ('Bonham','TX',true),
  ('Honey Grove','TX',true),
  ('Whitewright','TX',true),
  ('Tom Bean','TX',true),
  ('Howe','TX',true),
  ('Bells','TX',true),
  ('Denison','TX',true),
  ('Pottsboro','TX',true),
  ('Whitesboro','TX',true),
  ('Collinsville','TX',true),
  ('Tioga','TX',true),
  ('Valley View','TX',true),
  -- ── TEXAS: Northwest (Wichita Falls direction) ──
  ('Wichita Falls','TX',true),
  ('Burkburnett','TX',true),
  ('Iowa Park','TX',true),
  ('Electra','TX',true),
  ('Henrietta','TX',true),
  ('Bowie','TX',true),
  ('Nocona','TX',true),
  ('Saint Jo','TX',true),
  ('Sunset','TX',true),
  ('Alvord','TX',true),
  ('Chico','TX',true),
  ('Forestburg','TX',true),
  ('Era','TX',true),
  -- ── TEXAS: South / central ──
  ('Stephenville','TX',true),
  ('Dublin','TX',true),
  ('De Leon','TX',true),
  ('Comanche','TX',true),
  ('Hico','TX',true),
  ('Hamilton','TX',true),
  ('Goldthwaite','TX',true),
  ('Gatesville','TX',true),
  ('Copperas Cove','TX',true),
  ('Killeen','TX',true),
  ('Harker Heights','TX',true),
  ('Belton','TX',true),
  ('Temple','TX',true),
  ('Salado','TX',true),
  ('Holland','TX',true),
  ('Bartlett','TX',true),
  ('Granger','TX',true),
  ('Taylor','TX',true),
  ('Hutto','TX',true),
  -- ── TEXAS: Southeast ──
  ('Palestine','TX',true),
  ('Elkhart','TX',true),
  ('Frankston','TX',true),
  ('Brownsboro','TX',true),
  -- ── TEXAS: West of Fort Worth ──
  ('Eastland','TX',true),
  ('Cisco','TX',true),
  ('Ranger','TX',true),
  ('Strawn','TX',true),
  ('Mingus','TX',true),
  ('Gordon','TX',true),
  ('Santo','TX',true),
  ('Palo Pinto','TX',true),
  ('Graford','TX',true),
  ('Possum Kingdom','TX',true),
  ('Olney','TX',true),
  ('Throckmorton','TX',true),
  ('Graham','TX',true),
  ('Newcastle','TX',true),
  ('Loving','TX',true),
  ('Jacksboro','TX',true),
  ('Jermyn','TX',true)
ON CONFLICT (name) DO UPDATE SET is_active = true, state = EXCLUDED.state;

-- Re-activate every city that may have been deactivated
UPDATE cities SET is_active = true WHERE is_active IS NOT TRUE;
