-- 026_seed_cities_within_150mi.sql
-- Seed every city within ~150 miles of Denver and Dallas/Fort Worth so the
-- customer brain never fires "Customer order needs manual city assignment"
-- for a real geocoded address inside our service area.
--
-- Safe to re-run: ON CONFLICT updates is_active and avoids duplicates.

-- Make sure unique constraint exists (idempotent)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'cities_name_unique') THEN
    ALTER TABLE cities ADD CONSTRAINT cities_name_unique UNIQUE (name);
  END IF;
END $$;

-- Make sure is_active column exists (some installs may have it, some not)
DO $$ BEGIN
  ALTER TABLE cities ADD COLUMN IF NOT EXISTS is_active boolean DEFAULT true;
END $$;

-- ─────────────────────────────────────────────────────────
-- DENVER METRO + FRONT RANGE (within ~150 miles)
-- ─────────────────────────────────────────────────────────
INSERT INTO cities (name, is_active) VALUES
  -- Denver core
  ('Denver', true),
  ('Aurora', true),
  ('Lakewood', true),
  ('Thornton', true),
  ('Arvada', true),
  ('Westminster', true),
  ('Centennial', true),
  ('Englewood', true),
  ('Wheat Ridge', true),
  ('Littleton', true),
  ('Northglenn', true),
  ('Commerce City', true),
  ('Parker', true),
  ('Brighton', true),
  ('Greenwood Village', true),
  ('Edgewater', true),
  ('Sheridan', true),
  ('Federal Heights', true),
  ('Lone Tree', true),
  ('Golden', true),
  ('Highlands Ranch', true),
  ('Cherry Hills Village', true),
  ('Castle Rock', true),
  ('Castle Pines', true),
  ('Glendale', true),
  ('Mountain View', true),
  ('Lakeside', true),
  ('Bow Mar', true),
  ('Columbine Valley', true),
  ('Foxfield', true),
  ('Morrison', true),
  -- Boulder county
  ('Boulder', true),
  ('Longmont', true),
  ('Broomfield', true),
  ('Erie', true),
  ('Lafayette', true),
  ('Louisville', true),
  ('Superior', true),
  ('Niwot', true),
  ('Gunbarrel', true),
  ('Nederland', true),
  ('Jamestown', true),
  ('Ward', true),
  ('Allenspark', true),
  ('Lyons', true),
  -- Adams / Weld county north
  ('Dacono', true),
  ('Frederick', true),
  ('Firestone', true),
  ('Mead', true),
  ('Johnstown', true),
  ('Berthoud', true),
  ('Severance', true),
  ('Eaton', true),
  ('Ault', true),
  ('Pierce', true),
  ('Nunn', true),
  ('Carr', true),
  ('Wellington', true),
  ('Timnath', true),
  ('Windsor', true),
  ('Milliken', true),
  ('Platteville', true),
  ('Gilcrest', true),
  ('La Salle', true),
  ('Evans', true),
  ('Greeley', true),
  ('Kersey', true),
  ('Hudson', true),
  ('Keenesburg', true),
  ('Fort Lupton', true),
  ('Lochbuie', true),
  -- Fort Collins / Loveland area
  ('Fort Collins', true),
  ('Loveland', true),
  ('Estes Park', true),
  ('Drake', true),
  ('Glen Haven', true),
  ('Red Feather Lakes', true),
  ('Livermore', true),
  ('Bellvue', true),
  ('Laporte', true),
  -- South of Denver: Colorado Springs corridor (within 150mi)
  ('Colorado Springs', true),
  ('Monument', true),
  ('Palmer Lake', true),
  ('Larkspur', true),
  ('Sedalia', true),
  ('Franktown', true),
  ('Elizabeth', true),
  ('Kiowa', true),
  ('Elbert', true),
  ('Black Forest', true),
  ('Falcon', true),
  ('Peyton', true),
  ('Calhan', true),
  ('Ramah', true),
  ('Manitou Springs', true),
  ('Cascade', true),
  ('Green Mountain Falls', true),
  ('Woodland Park', true),
  ('Divide', true),
  ('Florissant', true),
  ('Cripple Creek', true),
  ('Victor', true),
  ('Fountain', true),
  ('Security-Widefield', true),
  ('Stratmoor', true),
  ('Cimarron Hills', true),
  ('Gleneagle', true),
  -- Mountain communities west of Denver
  ('Idaho Springs', true),
  ('Georgetown', true),
  ('Silver Plume', true),
  ('Empire', true),
  ('Black Hawk', true),
  ('Central City', true),
  ('Evergreen', true),
  ('Conifer', true),
  ('Bailey', true),
  ('Pine', true),
  ('Pine Junction', true),
  ('Indian Hills', true),
  ('Kittredge', true),
  ('Genesee', true),
  ('Aspen Park', true),
  ('Tiny Town', true),
  ('Buffalo Creek', true),
  -- Eastern plains
  ('Bennett', true),
  ('Strasburg', true),
  ('Byers', true),
  ('Watkins', true),
  ('Deer Trail', true),
  ('Agate', true),
  ('Limon', true),
  ('Hugo', true),
  ('Genoa', true),
  ('Arriba', true),
  ('Flagler', true),
  ('Last Chance', true),
  ('Akron', true),
  ('Otis', true),
  ('Yuma', true),
  ('Wray', true),
  ('Burlington', true),
  -- South-southeast: Pueblo direction (just under 150mi)
  ('Pueblo', true),
  ('Pueblo West', true),
  ('Penrose', true),
  ('Florence', true),
  ('Canon City', true),
  ('Cañon City', true),
  ('Lincoln Park', true),
  ('Salida', true),
  ('Buena Vista', true),
  ('Westcliffe', true),
  ('Walsenburg', true),
  -- North/northeast plains toward Sterling
  ('Roggen', true),
  ('Wiggins', true),
  ('Fort Morgan', true),
  ('Brush', true),
  ('Snyder', true),
  ('Sterling', true),
  ('Crook', true)
ON CONFLICT (name) DO UPDATE SET is_active = true;

-- ─────────────────────────────────────────────────────────
-- DALLAS / FORT WORTH outer ring + East/Central Texas (extending the
-- existing migration 019 to ~150 mi). Most are already there from 019,
-- this fills the rest and re-activates anything that drifted to inactive.
-- ─────────────────────────────────────────────────────────
INSERT INTO cities (name, is_active) VALUES
  -- East Texas (Tyler / Longview corridor)
  ('Tyler', true),
  ('Whitehouse', true),
  ('Lindale', true),
  ('Bullard', true),
  ('Flint', true),
  ('Chandler', true),
  ('Mineola', true),
  ('Quitman', true),
  ('Athens', true),
  ('Mabank', true),
  ('Gun Barrel City', true),
  ('Eustace', true),
  ('Trinidad', true),
  ('Malakoff', true),
  -- Waco corridor (just under 100 mi from Dallas)
  ('Waco', true),
  ('Hewitt', true),
  ('Robinson', true),
  ('Bellmead', true),
  ('Lacy Lakeview', true),
  ('Woodway', true),
  ('Lorena', true),
  ('McGregor', true),
  ('Hillsboro', true),
  ('West', true),
  ('Mart', true),
  ('Marlin', true),
  ('Crawford', true),
  ('Whitney', true),
  ('Aquilla', true),
  ('Itasca', true),
  ('Penelope', true),
  ('Mexia', true),
  ('Fairfield', true),
  ('Teague', true),
  ('Wortham', true),
  ('Groesbeck', true),
  -- Northeast Texas
  ('Sulphur Springs', true),
  ('Mount Pleasant', true),
  ('Mount Vernon', true),
  ('Winnsboro', true),
  ('Pittsburg', true),
  ('Daingerfield', true),
  ('Paris', true),
  ('Bonham', true),
  ('Honey Grove', true),
  ('Whitewright', true),
  ('Tom Bean', true),
  ('Howe', true),
  ('Bells', true),
  ('Denison', true),
  ('Pottsboro', true),
  ('Whitesboro', true),
  ('Collinsville', true),
  ('Tioga', true),
  ('Valley View', true),
  -- Northwest Texas (Wichita Falls direction)
  ('Wichita Falls', true),
  ('Burkburnett', true),
  ('Iowa Park', true),
  ('Electra', true),
  ('Henrietta', true),
  ('Bowie', true),
  ('Nocona', true),
  ('Saint Jo', true),
  ('Sunset', true),
  ('Alvord', true),
  ('Chico', true),
  ('Forestburg', true),
  ('Era', true),
  -- South / central Texas (within 150 mi of DFW)
  ('Stephenville', true),
  ('Dublin', true),
  ('De Leon', true),
  ('Comanche', true),
  ('Hico', true),
  ('Hamilton', true),
  ('Goldthwaite', true),
  ('Gatesville', true),
  ('Copperas Cove', true),
  ('Killeen', true),
  ('Harker Heights', true),
  ('Belton', true),
  ('Temple', true),
  ('Salado', true),
  ('Holland', true),
  ('Bartlett', true),
  ('Granger', true),
  ('Taylor', true),
  ('Hutto', true),
  -- Southeast Texas (Athens-Tyler-Palestine direction)
  ('Palestine', true),
  ('Elkhart', true),
  ('Frankston', true),
  ('Brownsboro', true),
  -- West of Fort Worth (Stephenville/Eastland direction, within 150 mi)
  ('Eastland', true),
  ('Cisco', true),
  ('Ranger', true),
  ('Strawn', true),
  ('Mingus', true),
  ('Gordon', true),
  ('Santo', true),
  ('Palo Pinto', true),
  ('Graford', true),
  ('Possum Kingdom', true),
  ('Olney', true),
  ('Throckmorton', true),
  ('Graham', true),
  ('Newcastle', true),
  ('Loving', true),
  ('Jacksboro', true),
  ('Jermyn', true)
ON CONFLICT (name) DO UPDATE SET is_active = true;

-- ─────────────────────────────────────────────────────────
-- Re-activate every city that may have been deactivated, just in case
-- the row was inserted by an older migration with is_active=false.
-- ─────────────────────────────────────────────────────────
UPDATE cities SET is_active = true WHERE is_active IS NOT TRUE;
